Repository baza-trainee/cat_for_future, pull requests merged in 2023-09, with the labels that each got.

#61 Feat/13 our cats section
  src/assets/images/cats/cat-1.jpg
  src/assets/images/cats/cat-2.jpg
  src/assets/images/cats/cat-3.jpg
  src/assets/images/cats/cat-4.jpg
  src/assets/images/cats/cat-5.jpg
  src/assets/images/cats/cat-6.jpg
  src/components/CatCard/CatCard.module.scss
  src/components/CatCard/CatCard.tsx
  src/components/CatCard/ImageCatCard/ImageCatCard.tsx
  src/components/CatCard/ImageSlider/ImageSlider.module.scss
  src/components/CatCard/ImageSlider/ImageSlider.tsx
  src/components/OurCats/OurCats.module.scss
  src/components/OurCats/OurCats.tsx
  src/data/cats.temp.ts
  src/pages/Home/Home.module.scss
  src/pages/Home/Home.tsx
  src/types/ICat.ts
  src/utils/pluralize.ts
Labels: feature

#65 refactor: refactor slider, change cat-img imports
  src/components/CatCard/CatCard.tsx
  src/components/Slider/Slider.module.scss
  src/components/Slider/Slider.tsx
  src/data/cats.temp.ts
Labels: refactor

#75 Feat/25 show cat modal
  .husky/pre-commit
  src/assets/images/cats/cat-1.jpg
  src/assets/images/cats/cat-2.jpg
  src/assets/images/cats/cat-3.jpg
  src/assets/images/cats/cat-4.jpg
  src/assets/images/cats/cat-5.jpg
  src/assets/images/cats/cat-6.jpg
  src/components/CatCard/Carousel/Carousel.module.scss
  src/components/CatCard/Carousel/Carousel.tsx
  src/components/CatCard/CatCard.module.scss
  src/components/CatCard/CatCard.tsx
  src/components/CatCard/ImageCatCard/ImageCatCard.module.scss
  src/components/CatCard/ImageCatCard/ImageCatCard.tsx
  src/components/CatCard/ModalShowCat/ModalShowCat.module.scss
  src/components/CatCard/ModalShowCat/ModalShowCat.tsx
  src/components/ModalWhiteCat/ModalWhiteCat.module.scss
  src/components/OurCats/OurCats.tsx
  src/components/Slider/Slider.module.scss
  src/data/cats.temp.ts
  src/utils/pluralize.ts
Labels: feature

#80 Fix/17 bug cat card modal
  src/components/CatCard/CatCard.tsx
  src/components/OurCats/OurCats.tsx
Labels: fix

#82 Feat/27 happy stories
  src/components/Button/Button.module.scss
  src/components/Contacts/Contacts.module.scss
  src/components/HappyStories/HappyStories.module.scss
  src/components/HappyStories/HappyStories.tsx
  src/components/HappyStories/StoryCard/StoryCard.module.scss
  src/components/Header/Header.module.scss
  src/components/Menu/Menu.module.scss
  src/components/Page404/Page404.tsx
  src/pages/Home/Home.tsx
  src/styles/_mixins.scss
  src/utils/scrollToSection.ts
Labels: fix

#84 Fix/21 carousel bug
  src/components/CatCard/Carousel/Carousel.tsx
  src/components/CatCard/CatCard.tsx
  src/data/cats.temp.ts
Labels: fix
