Repository baza-trainee/cat_for_future, pull requests merged in 2023-10, with the labels that each got.

#98 Feat/33 change password account
  src/assets/images/green_check.png
  src/components/Account/AccountBlocks/ChangePassword/ChangePassword.module.scss
  src/components/Account/AccountBlocks/ChangePassword/ChangePassword.tsx
  src/components/Account/AccountBlocks/ChangePassword/InputPassword/InputPassword.module.scss
  src/components/Account/AccountBlocks/ChangePassword/InputPassword/InputPassword.tsx
  src/components/Account/AccountBlocks/ChangePassword/changePassword.schema.ts
  src/components/ModalBack/ModalBack.module.scss
  src/components/ModalBack/ModalBack.tsx
  src/components/ModalMsg/ModalMsg.module.scss
  src/components/ModalMsg/ModalMsg.tsx
Labels: feature

#102 Feat/33 change password account
  src/components/Account/AccountBlocks/ChangePassword/ChangePassword.tsx
  src/components/InputPassword/InputPassword.module.scss
  src/components/InputPassword/InputPassword.tsx
  src/components/ModalBack/ModalBack.module.scss
Labels: fix

#111 Feat/38 confirm recovery password
  src/App.tsx
  src/components/Account/AccountBlocks/ChangePassword/ChangePassword.tsx
  src/components/ConfirmPasswordForm/ConfirmPasswordForm.module.scss
  src/components/ConfirmPasswordForm/ConfirmPasswordForm.tsx
  src/components/Header/Header.tsx
  src/components/InputPassword/InputPassword.module.scss
  src/components/Layout/Layout.tsx
  src/components/Login/Login.tsx
  src/components/ModalBack/ModalBack.tsx
  src/hooks/useActions.ts
  src/hooks/useTypedSelectors.ts
  src/pages/Home/Home.tsx
  src/pages/RegistrationPage/RegPageIndex.tsx
  src/schemas/changePassword.schema.ts
  src/schemas/confirmPassword.schema.ts
  src/store/slice/showLoginSlice.ts
  src/store/store.ts
  src/store/useActions.ts
  src/store/useTypedSelectors.ts
Labels: feature

#117 Feat/39 request recovery password
  src/components/Account/AccountBlocks/ChangePassword/ChangePassword.tsx
  src/components/ModalMsg/ModalMsg.tsx
  src/schemas/changePassword.schema.ts
  src/schemas/confirmPassword.schema.ts
Labels: fix

#118 fix: add style to modal btn, fix close modal
  src/components/ConfirmPasswordForm/ConfirmPasswordForm.tsx
Labels: fix

#121 Feat/39 request recovery password
  src/components/RequestPasswordForm/RequestPasswordForm.module.scss
  src/components/RequestPasswordForm/RequestPasswordForm.tsx
  src/schemas/requestPassword.schema.ts
  src/styles/_reset.scss
  src/styles/_variables.scss
Labels: fix

#124 Feat/39 request recovery password
  src/components/ModalBack/ModalBack.module.scss
  src/components/ModalBack/ModalBack.tsx
  src/hooks/useEscape.ts
  src/utils/onClickModalBack.ts
Labels: feature

#125 Refactor/cat modal
  src/components/CatCard/CatCard.module.scss
  src/components/CatCard/CatCard.tsx
  src/components/CatCard/ModalShowCat/ModalShowCat.tsx
  src/components/OurCats/OurCats.module.scss
  src/components/OurCats/OurCats.tsx
  src/data/cats.temp.ts
Labels: refactor

#128 Feat/39 request recovery password
  src/hooks/useEscape.ts
Labels: fix
